### ISSUE TITLE
Manifesto needs a how-to link ~ and how-not-to

### ISSUE THREAD

**Issue by jasonbrown1965** [open-organization-ambassadors/open-org-definition#16]
As the editor for an all-volunteer media freedom and ethics non-profit* covering the world's largest (ocean) region, I've been advocating open org approaches for over ten years now.**

So I was most interested to read the open org article which this repository stems from. Agree with everything it says, but cautions should be applied. 

Yes, there are suggested links at the bottom of the page exploring pros and cons in greater depth, but nothing that breaks down potential pitfalls or, in my case, pratfalls.

An example from our org, I leapt in boots and all and gave my fellow email group admins equal players on the website we created for our organisation. Open, right? Because it was so simple and easy using new website tools (blogger.com all those years ago) we could all be admins!

Wrong. Formatting that I'd spent weeks refining got mucked up, and pages that I'd spent hours on simply disappeared. No one had time to answer my questions, much less collaborate. We lost two websites in a row to squatters because of open collaboration - everyone agreed to do things, but then didn't do them.

It was with grim reluctance I came to admit to myself that the term 'webmaster' is there for a reason - to protect mission-critical areas in any organisation that cannot and should not be 'open' - at least not until that organisation has got the capacity to handle it.

If anyone needs help writing a how-not-to piece be happy to provide my expertise! 

* [Pacific Freedom Forum](https://facebook.com/pacificfreedomforum)
** [TTT | TotalTransparencyTools](http://totaltransparencytools.blogspot.com) - an early draft that badly needs updating. The basic triple-T premise is - learn the Tools, test some Techniques, and only then attempt Transformation.

**Comment by semioticrobotic** [comment]
Thanks for reaching out, @jasonbrown1965. We really appreciate your connecting with us.

Our community just released its own "how-to" guide in the form of _The Open Organization Workbook_. You'll find that resource [right here on GitHub](https://github.com/open-organization-ambassadors/open-org-workbook). We'd love to hear your thoughts on it.

As the for other end of that all-important spectrum, the "how-not-to" part: That's a rather popular format for articles in the Open Organization section of Opensource.com. As we like to say, failures are instructive, and our community always appreciates when folks share stories of their trials and tribulations in the spirit of helping others avoid potential "pitfalls and pratfalls."

We'd be happy to work with you to bring your stories to our audience. Your decade of experience would be a source of knowledge for our readers, and your candor would be very welcome!
