### ISSUE TITLE
Create Waffle board for Open Org definition

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-definition#3]
I wanted to offer up the following, a Waffle.io board to help bridge the gap between GitHub semantics and contributing.

https://waffle.io/opensourceway/open-org-definition

I know that GitHub can be intimidating for many people and Waffle offers a graphical interface and makes it easy to add issues and comment on things. 

Also, once you sign up for a GitHub account you can get email updates and interact with issues completely through email--meaning you can make comments on the issues through email.

Please let us know if you have questions about using GitHub or Waffle.

**Comment by chadwhitacre** [comment]
P.S. Check out [projects](https://github.com/opensourceway/open-org-definition/projects) if you haven't yet ... GitHub-native kanban boards! 💃
