### ISSUE TITLE
Explore potential areas of overlap/resonance between us and the McChrystal group

### ISSUE THREAD

**Issue by amatlack** [open-organization-ambassadors/open-org-definition#4]
The McChrystal group "was founded in order to help businesses challenge the hierarchical, command and control approach to organizational management. Our client is the 21st century organization that wants to cut through complexity and drive sustained adaptability at the enterprise level, consistently improving performance in a constantly shifting environment." [[1]](https://mcchrystalgroup.com/about-mcchrystal-group/vision-mission/)

CrossLead [[2]](https://www.crosslead.com/our-team/) spun off from the McChrystal group to scale Enterprise services, and their framework [[3]](https://www.crosslead.com/about/our-framework/) seems right in line with what we're trying to define here.

I would love to see if we can connect with someone in the McChrystal universe to see how we can help each other reach seemingly similar goals.

**Comment by jhibbets** [comment]
Bryan and I are looking to make some connections with the McChrystal group
to gauge their interest in a webcast in the spring and then go from there.

**Comment by chadwhitacre** [comment]
What would be the outcome here? Are we talking about perhaps recruiting another Ambassador?

**Comment by semioticrobotic** [comment]
I think one initial goal would be to explore potential areas of overlap/resonance between that team's thinking and our own. We suspect a webcast might be a nice way to do that.

**Comment by chadwhitacre** [comment]
> a webcast in the spring
> a webcast might be a nice way to do that

Perhaps we could retitle this ticket to reflect that scope?

**Comment by semioticrobotic** [comment]
I'm closing this issue in the hope that we may one day reopen it when we've made the appropriate connections. At the moment, it doesn't concretely connect to our work on the Open Organization Definition.
