### ISSUE TITLE
Recruit an Ambassador from the sharing economy universe

### ISSUE THREAD

**Issue by chadwhitacre** [open-organization-ambassadors/open-org-definition#5]
Inspired by @amatlack in #4—in 2017 could we recruit an Ambassador from the sharing economy "universe"? Some starting points:

http://platformcoop.net/
http://www.shareable.net/
http://ouishare.net/en
https://medium.com/enspiral-tales/about
https://2017.open.coop

**Comment by chadwhitacre** [comment]
@LauraHilliger, you are connected with Doug Belshaw who is [speaking](https://2017.open.coop/contributors/dr-doug-belshaw/) at https://2017.open.coop/, ya?

**Comment by LauraHilliger** [comment]
Yup, we're in cahoots @dajbelshaw and me

--from laura on a mobile device, likely typed in haste.

**Comment by chadwhitacre** [comment]
There's an outside chance I will make it to London next month. If so I would love to meet, @dajbelshaw! :-)

**Comment by semioticrobotic** [comment]
I am always open to making these connections but am closing this at the moment because it is not directly related to work on the Open Organization Definition.
