### ISSUE TITLE
Change the sharing on Open Org Maturity Model doc

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization-ambassadors/open-org-definition#9]
Just wanted to share this doc in progress and noticed that it isn't open. Only people at Red Hat and the Ambassadors have access? Can we make it that anyone can comment?

**Comment by semioticrobotic** [comment]
Thanks for addressing this, @LauraHilliger. I agree that we need to develop a better toolchain for making early-stage drafting materials more widely available and transparent. I will think on that and hope others will, too.

In the meantime, the first complete draft of the maturity model language is [now live](https://github.com/open-organization-ambassadors/open-org-definition/issues/7#issuecomment-291288616). Please circulate widely and well so we can get the best feedback possible.
